In [1]:
import numpy as np

In [2]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print X

[[  2.79271702 -14.8471058    8.01128229 ...,   6.15222658  15.22713697
   15.43069883]
 [-14.65135316  10.3637282   -9.20252277 ...,   0.04371476  -7.49485562
   17.71162128]
 [ 23.88993414   6.25764267   5.34010644 ...,  -9.16954294   3.46478363
   10.3991795 ]
 ..., 
 [-11.33941942  -9.57203307  13.03256267 ...,   9.91585098  -7.26831049
   13.48506513]
 [ -2.07897313  18.97850136   5.80416123 ...,   5.24185785  -0.63388405
    3.57519544]
 [-22.24507705  -5.87426815  -7.29016995 ...,  -2.87561295   0.54378982
   14.90291363]]


In [3]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print X_norm

[[ 0.18370413 -1.5091566   0.71351858 ...,  0.58567749  1.38176763
   1.44807277]
 [-1.51265783  0.90323342 -1.01066136 ..., -0.00554487 -0.86686269
   1.67572659]
 [ 2.23531915  0.51032774  0.44596659 ..., -0.89726517  0.21773309
   0.94588798]
 ..., 
 [-1.1905863  -1.00439215  1.21646321 ...,  0.94994606 -0.84444316
   1.25388338]
 [-0.29004711  1.72756921  0.49244753 ...,  0.49756595 -0.18788224
   0.26480125]
 [-2.25111532 -0.65055811 -0.81911508 ..., -0.2880968  -0.07133642
   1.3953957 ]]


In [4]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [5]:
r = np.sum(Z, axis=1)
print np.nonzero(r > 10)

(array([1, 4, 5]),)


In [6]:
A = np.eye(3)
B = np.eye(3)
print A
print B

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
AB = np.vstack((A, B))
print AB

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
